name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-linux:
    name: Test & Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig installation
        run: |
          set -euo pipefail
          zig version
          which zig

      - name: Build nen-net
        run: |
          set -euo pipefail
          zig build

      - name: Run tests
        run: |
          set -euo pipefail
          zig build test

      - name: Run integration tests
        run: |
          set -euo pipefail
          zig build test-integration

      - name: Run performance tests
        run: |
          set -euo pipefail
          zig build test-perf

      - name: Run memory tests
        run: |
          set -euo pipefail
          zig build test-memory

      - name: Run stress tests
        run: |
          set -euo pipefail
          zig build test-stress

      # Examples removed - will be added when core functionality is implemented
      # - name: Build examples
      #   run: |
      #     set -euo pipefail
      #     zig build examples

      - name: Build benchmarks
        run: |
          set -euo pipefail
          zig build benchmark

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nen-net-linux-build
          path: zig-out/

  test-macos:
    name: Test & Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig installation
        run: |
          set -euo pipefail
          zig version
          which zig

      - name: Build nen-net
        run: |
          set -euo pipefail
          zig build

      - name: Run tests
        run: |
          set -euo pipefail
          zig build test

      - name: Run integration tests
        run: |
          set -euo pipefail
          zig build test-integration

      - name: Run performance tests
        run: |
          set -euo pipefail
          zig build test-perf

      - name: Run memory tests
        run: |
          set -euo pipefail
          zig build test-memory

      - name: Run stress tests
        run: |
          set -euo pipefail
          zig build test-stress

      # Examples removed - will be added when core functionality is implemented
      # - name: Build examples
      #   run: |
      #     set -euo pipefail
      #     zig build examples

      - name: Build benchmarks
        run: |
          set -euo pipefail
          zig build benchmark

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nen-net-macos-build
          path: zig-out/

  test-windows:
    name: Test & Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Zig 0.15.1
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify Zig installation
        run: |
          zig version
          where zig

      - name: Build nen-net
        run: |
          zig build

      - name: Run tests
        run: |
          zig build test

      - name: Run integration tests
        run: |
          zig build test-integration

      - name: Run performance tests
        run: |
          zig build test-perf

      - name: Run memory tests
        run: |
          zig build test-memory

      - name: Run stress tests
        run: |
          zig build test-stress

      - name: Build examples
        run: |
          zig build examples

      - name: Build benchmarks
        run: |
          zig build benchmark

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nen-net-windows-build
          path: zig-out/