name: Format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        zig-version: 0.15.1

    - name: Check formatting
      run: |
        echo "🎨 Checking code formatting"
        zig fmt --check .
        echo "✅ Code formatting is correct"
